#!/usr/bin/env bash
# scan.sh — detect new/changed/removed sources in raw/ vs the ingest manifest.
#
# Each top-level entry in raw/ is one source (file, directory, or symlink to a living
# document). Fingerprints follow symlinks. The diff is against .ingest/manifest.tsv.
#
#   ./scan.sh            detect; write .ingest/pending.md; exit 0 = clean, 10 = pending
#   ./scan.sh --accept   advance the manifest baseline to current state (used post-ingest)
#
# No LLM, no network, no cost. Portable across macOS (bash 3.2 / BSD tools) and Linux.

set -euo pipefail

die() { printf 'scan: error: %s\n' "$1" >&2; exit 1; }

MODE="detect"
[ "${1:-}" = "--accept" ] && MODE="accept"

KB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RAW_DIR="$KB_DIR/raw"
STATE_DIR="$KB_DIR/.ingest"
MANIFEST="$STATE_DIR/manifest.tsv"
PENDING="$STATE_DIR/pending.md"
DATE="$(date +%F)"

MANIFEST_HEADER=$'# manifest.tsv — ingest baseline. Columns: source_path\tkind\tfingerprint\tlast_ingested\n# Managed by scripts/scan.sh (--accept). Do not edit by hand.'

[ -d "$RAW_DIR" ] || die "no raw/ at $RAW_DIR"
mkdir -p "$STATE_DIR"
[ -f "$MANIFEST" ] || printf '%s\n' "$MANIFEST_HEADER" > "$MANIFEST"

# --- portable hashing + stat -------------------------------------------------
if command -v shasum >/dev/null 2>&1; then
  _hash() { shasum -a 256 | cut -d' ' -f1; }
elif command -v sha256sum >/dev/null 2>&1; then
  _hash() { sha256sum | cut -d' ' -f1; }
else
  die "need shasum or sha256sum on PATH"
fi

if stat -f '%z' . >/dev/null 2>&1; then
  _statline() { stat -f '%z %m' "$1"; }   # BSD / macOS: <size> <mtime>
else
  _statline() { stat -c '%s %Y' "$1"; }   # GNU / Linux
fi

# fingerprint = hash of (relative-path size mtime) for every file under the source,
# sorted for stability. Follows symlinks (-L) so living symlink targets are covered.
fingerprint() {
  find -L "$1" -type f 2>/dev/null | LC_ALL=C sort | while IFS= read -r f; do
    printf '%s %s\n' "$f" "$(_statline "$f")"
  done | _hash
}

kind_of() {
  if [ -L "$1" ]; then echo "symlink-living"
  elif [ -d "$1" ]; then echo "directory"
  else echo "file"; fi
}

SEEN_FILE="$(mktemp)"; trap 'rm -f "$SEEN_FILE"' EXIT
NEW=(); CHANGED=(); NEWMAN=()

shopt -s nullglob
for src in "$RAW_DIR"/*; do
  base="$(basename "$src")"
  case "$base" in README.md|.*) continue;; esac
  rel="raw/$base"
  printf '%s\n' "$rel" >> "$SEEN_FILE"
  fp="$(fingerprint "$src")"
  kind="$(kind_of "$src")"
  prior_line="$(awk -F'\t' -v p="$rel" '$1==p{print; exit}' "$MANIFEST")"
  if [ -z "$prior_line" ]; then
    NEW+=("$rel ($kind)"); last="$DATE"
  else
    prior_fp="$(printf '%s' "$prior_line" | cut -f3)"
    prior_last="$(printf '%s' "$prior_line" | cut -f4)"
    if [ "$prior_fp" != "$fp" ]; then
      CHANGED+=("$rel ($kind)"); last="$DATE"
    else
      last="${prior_last:-$DATE}"
    fi
  fi
  NEWMAN+=("$rel	$kind	$fp	$last")
done
shopt -u nullglob

# removed = rows in the manifest whose path no longer exists in raw/
REMOVED=()
while IFS=$'\t' read -r path _k _f _l; do
  case "${path:-}" in ''|'#'*) continue;; esac
  grep -qxF "$path" "$SEEN_FILE" || REMOVED+=("$path")
done < "$MANIFEST"

# --- accept: rewrite manifest to current state, then stop --------------------
if [ "$MODE" = "accept" ]; then
  { printf '%s\n' "$MANIFEST_HEADER"
    for row in "${NEWMAN[@]:-}"; do [ -n "$row" ] && printf '%s\n' "$row"; done
  } > "$MANIFEST"
  printf '# Pending ingest\n\n_Baseline accepted on %s — nothing pending._\n' "$DATE" > "$PENDING"
  printf 'scan: baseline advanced (%d sources). Manifest up to date.\n' "${#NEWMAN[@]}"
  exit 0
fi

# --- write pending.md --------------------------------------------------------
{
  printf '# Pending ingest — generated by scan.sh on %s\n\n' "$DATE"
  printf '_Do not edit by hand; regenerated on every scan._\n\n'
  printf '## New (%d)\n' "${#NEW[@]}"
  if [ "${#NEW[@]}" -eq 0 ]; then printf '_none_\n'; else for x in "${NEW[@]}"; do printf -- '- `%s`\n' "$x"; done; fi
  printf '\n## Changed (%d)\n' "${#CHANGED[@]}"
  if [ "${#CHANGED[@]}" -eq 0 ]; then printf '_none_\n'; else for x in "${CHANGED[@]}"; do printf -- '- `%s`\n' "$x"; done; fi
  printf '\n## Removed (%d)\n' "${#REMOVED[@]}"
  if [ "${#REMOVED[@]}" -eq 0 ]; then printf '_none_\n'; else for x in "${REMOVED[@]}"; do printf -- '- `%s`\n' "$x"; done; fi
} > "$PENDING"

PEND=$(( ${#NEW[@]} + ${#CHANGED[@]} + ${#REMOVED[@]} ))
printf 'scan: %d new, %d changed, %d removed → %s\n' \
  "${#NEW[@]}" "${#CHANGED[@]}" "${#REMOVED[@]}" "${PENDING#"$KB_DIR"/}"
[ "$PEND" -eq 0 ] && exit 0 || exit 10
